-- ============================================
-- MIGRACIÓN 06: Email en casas + tabla correos_casa
-- Fecha: 2026-03-28
-- ============================================

-- 1. Agregar columna email_principal a tabla casas (nullable)
ALTER TABLE public.casas
    ADD COLUMN IF NOT EXISTS email_principal TEXT;

-- 2. Crear tabla correos_casa para correos adicionales
CREATE TABLE IF NOT EXISTS public.correos_casa (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    casa_id     BIGINT NOT NULL REFERENCES public.casas(id) ON DELETE CASCADE,
    email       TEXT   NOT NULL,
    etiqueta    TEXT,                          -- ej. "Propietario", "Contador"
    activo      BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT correos_casa_email_check CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

-- 3. Índice para consultas por casa
CREATE INDEX IF NOT EXISTS idx_correos_casa_casaid ON public.correos_casa(casa_id);

-- 4. Evitar duplicados de email por casa
CREATE UNIQUE INDEX IF NOT EXISTS idx_correos_casa_unique
    ON public.correos_casa(casa_id, LOWER(email));

-- 5. RLS: habilitar y permitir acceso autenticado
ALTER TABLE public.correos_casa ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "correos_casa_authenticated"
    ON public.correos_casa
    FOR ALL
    TO authenticated
    USING (TRUE)
    WITH CHECK (TRUE);
