-- ============================================
-- FIX RLS: tabla correos_casa
-- Ejecutar en: Supabase Dashboard → SQL Editor
-- ============================================

-- 1. Asegurarse de que la tabla existe con la estructura correcta
CREATE TABLE IF NOT EXISTS public.correos_casa (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    casa_id        BIGINT NOT NULL REFERENCES public.casas(id) ON DELETE CASCADE,
    email          TEXT   NOT NULL,
    etiqueta       TEXT,
    activo         BOOLEAN NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    CONSTRAINT correos_casa_email_check CHECK (email ~* '^[^@\s]+@[^@\s]+\.[^@\s]+$')
);

-- 2. Índice por casa
CREATE INDEX IF NOT EXISTS idx_correos_casa_casaid
    ON public.correos_casa(casa_id);

-- 3. Índice único para evitar duplicados de email por casa
CREATE UNIQUE INDEX IF NOT EXISTS idx_correos_casa_unique
    ON public.correos_casa(casa_id, LOWER(email));

-- 4. Habilitar RLS
ALTER TABLE public.correos_casa ENABLE ROW LEVEL SECURITY;

-- 5. Eliminar política anterior si existe (para recrearla limpia)
DROP POLICY IF EXISTS "correos_casa_authenticated" ON public.correos_casa;

-- 6. Crear política que permite todas las operaciones a usuarios autenticados
CREATE POLICY "correos_casa_authenticated"
    ON public.correos_casa
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
